import * as fs from "fs";

type Calendar = {
	months: Month[];
};

type Month = {
	name: string;
	number: number;
	days: Day[];
};

type Day = {
	date: number;
	type: string;
};

// Placeholder for the provided JSON data
const inputJSON = {
	"August 2023": {
		"1": "None",
		"2": "None",
		"3": "None",
		"4": "None",
		"5": "None",
		"6": "None",
		"7": "None",
		"8": "None",
		"9": "Orange",
		"10": "Blue",
		"11": "Orange",
		"12": "None",
		"13": "None",
		"14": "None",
		"15": "Blue",
		"16": "Orange",
		"17": "Blue",
		"18": "Orange",
		"19": "None",
		"20": "None",
		"21": "Blue",
		"22": "Orange",
		"23": "Blue",
		"24": "Orange",
		"25": "Blue",
		"26": "None",
		"27": "None",
		"28": "Orange",
		"29": "Blue",
		"30": "Orange",
		"31": "Blue",
	},
	"September 2023": {
		"1": "Orange",
		"2": "None",
		"3": "None",
		"4": "None",
		"5": "Orange",
		"6": "Blue",
		"7": "Orange",
		"8": "Blue",
		"9": "None",
		"10": "None",
		"11": "Orange",
		"12": "Blue",
		"13": "Orange",
		"14": "Blue",
		"15": "Orange",
		"16": "None",
		"17": "None",
		"18": "Blue",
		"19": "Orange",
		"20": "Blue",
		"21": "Orange",
		"22": "Blue",
		"23": "None",
		"24": "None",
		"25": "Orange",
		"26": "Blue",
		"27": "Orange",
		"28": "Blue",
		"29": "Orange",
		"30": "None",
	},
	"October 2023": {
		"1": "None",
		"2": "None",
		"3": "Orange",
		"4": "Blue",
		"5": "Orange",
		"6": "None",
		"7": "None",
		"8": "None",
		"9": "None",
		"10": "Blue",
		"11": "Orange",
		"12": "Blue",
		"13": "Orange",
		"14": "None",
		"15": "None",
		"16": "Blue",
		"17": "Orange",
		"18": "Blue",
		"19": "Orange",
		"20": "Blue",
		"21": "None",
		"22": "None",
		"23": "Orange",
		"24": "Blue",
		"25": "Orange",
		"26": "Blue",
		"27": "Orange",
		"28": "None",
		"29": "None",
		"30": "Blue",
		"31": "Orange",
	},
	"November 2023": {
		"1": "Blue",
		"2": "Orange",
		"3": "Blue",
		"4": "None",
		"5": "None",
		"6": "Orange",
		"7": "Blue",
		"8": "Blue",
		"9": "Orange",
		"10": "Blue",
		"11": "None",
		"12": "None",
		"13": "Orange",
		"14": "Blue",
		"15": "Orange",
		"16": "Blue",
		"17": "Orange",
		"18": "None",
		"19": "None",
		"20": "Blue",
		"21": "Orange",
		"22": "Blue",
		"23": "Orange",
		"24": "None",
		"25": "None",
		"26": "None",
		"27": "Orange",
		"28": "Blue",
		"29": "Orange",
		"30": "Blue",
	},
	"December 2023": {
		"1": "Orange",
		"2": "None",
		"3": "None",
		"4": "Blue",
		"5": "Orange",
		"6": "Blue",
		"7": "Orange",
		"8": "Blue",
		"9": "None",
		"10": "None",
		"11": "Orange",
		"12": "Blue",
		"13": "Orange",
		"14": "Blue",
		"15": "Orange",
		"16": "None",
		"17": "None",
		"18": "None",
		"19": "None",
		"20": "None",
		"21": "None",
		"22": "None",
		"23": "None",
		"24": "None",
		"25": "None",
		"26": "None",
		"27": "None",
		"28": "None",
		"29": "None",
		"30": "None",
		"31": "None",
	},
	"January 2024": {
		"1": "None",
		"2": "None",
		"3": "Blue",
		"4": "Orange",
		"5": "Blue",
		"6": "None",
		"7": "None",
		"8": "Orange",
		"9": "Blue",
		"10": "Orange",
		"11": "Blue",
		"12": "Orange",
		"13": "None",
		"14": "None",
		"15": "None",
		"16": "Blue",
		"17": "Orange",
		"18": "Blue",
		"19": "Orange",
		"20": "None",
		"21": "None",
		"22": "Blue",
		"23": "Orange",
		"24": "Blue",
		"25": "Orange",
		"26": "Blue",
		"27": "None",
		"28": "None",
		"29": "Orange",
		"30": "Blue",
		"31": "Orange",
	},
	"February 2024": {
		"1": "None",
		"2": "None",
		"3": "None",
		"4": "None",
		"5": "Orange",
		"6": "Blue",
		"7": "Orange",
		"8": "Blue",
		"9": "Orange",
		"10": "None",
		"11": "None",
		"12": "Blue",
		"13": "None",
		"14": "Orange",
		"15": "Blue",
		"16": "Orange",
		"17": "None",
		"18": "None",
		"19": "Blue",
		"20": "Orange",
		"21": "Blue",
		"22": "Orange",
		"23": "Blue",
		"24": "None",
		"25": "None",
		"26": "Orange",
		"27": "Blue",
		"28": "Orange",
		"29": "Blue",
	},
	"March 2024": {
		"1": "None",
		"2": "None",
		"3": "None",
		"4": "None",
		"5": "None",
		"6": "Blue",
		"7": "None",
		"8": "None",
		"9": "None",
		"10": "None",
		"11": "None",
		"12": "None",
		"13": "None",
		"14": "None",
		"15": "None",
		"16": "None",
		"17": "None",
		"18": "None",
		"19": "Orange",
		"20": "Blue",
		"21": "Orange",
		"22": "Blue",
		"23": "None",
		"24": "None",
		"25": "Orange",
		"26": "Blue",
		"27": "Orange",
		"28": "Blue",
		"29": "None",
		"30": "None",
		"31": "None",
	},
	"April 2024": {
		"1": "Orange",
		"2": "Blue",
		"3": "Orange",
		"4": "Blue",
		"5": "None",
		"6": "None",
		"7": "None",
		"8": "Orange",
		"9": "Blue",
		"10": "Orange",
		"11": "Blue",
		"12": "Orange",
		"13": "None",
		"14": "None",
		"15": "Blue",
		"16": "Orange",
		"17": "Blue",
		"18": "Orange",
		"19": "None",
		"20": "None",
		"21": "None",
		"22": "Blue",
		"23": "Orange",
		"24": "Blue",
		"25": "Orange",
		"26": "Blue",
		"27": "None",
		"28": "None",
		"29": "Orange",
		"30": "Blue",
	},
	"May 2024": {
		"1": "Orange",
		"2": "Blue",
		"3": "None",
		"4": "None",
		"5": "None",
		"6": "Orange",
		"7": "Blue",
		"8": "Orange",
		"9": "Blue",
		"10": "Orange",
		"11": "None",
		"12": "None",
		"13": "Blue",
		"14": "Orange",
		"15": "Blue",
		"16": "Orange",
		"17": "Blue",
		"18": "None",
		"19": "None",
		"20": "Orange",
		"21": "Blue",
		"22": "Orange",
		"23": "Blue",
		"24": "Blue",
		"25": "None",
		"26": "None",
		"27": "None",
		"28": "None",
		"29": "Orange",
		"30": "Blue",
		"31": "None",
	},
	"June 2024": {
		"1": "None",
		"2": "None",
		"3": "None",
		"4": "None",
		"5": "None",
		"6": "None",
		"7": "None",
		"8": "None",
		"9": "None",
		"10": "None",
		"11": "None",
		"12": "None",
		"13": "None",
		"14": "None",
		"15": "None",
		"16": "None",
		"17": "None",
		"18": "None",
		"19": "None",
		"20": "None",
		"21": "None",
		"22": "None",
		"23": "None",
		"24": "None",
		"25": "None",
		"26": "None",
		"27": "None",
		"28": "None",
		"29": "None",
		"30": "None",
	},
	"July 2024": {
		"1": "None",
		"2": "None",
		"3": "None",
		"4": "None",
		"5": "None",
		"6": "None",
		"7": "None",
		"8": "None",
		"9": "None",
		"10": "None",
		"11": "None",
		"12": "None",
		"13": "None",
		"14": "None",
		"15": "None",
		"16": "None",
		"17": "None",
		"18": "None",
		"19": "None",
		"20": "None",
		"21": "None",
		"22": "None",
		"23": "None",
		"24": "None",
		"25": "None",
		"26": "None",
		"27": "None",
		"28": "None",
		"29": "None",
		"30": "None",
		"31": "None",
	},
};
const monthNumbers: { [key: string]: number } = {
	january: 1,
	february: 2,
	march: 3,
	april: 4,
	may: 5,
	june: 6,
	july: 7,
	august: 8,
	september: 9,
	october: 10,
	november: 11,
	december: 12,
};
function transformData(inputData: any): Calendar {
	const months: Month[] = Object.keys(inputData).map((monthName) => {
		const daysArray = [];
		for (const [date, color] of Object.entries(inputData[monthName])) {
			const day: Day = {
				date: Number(date),
				type: color,
			};
			daysArray.push(day);
		}
		return {
			name: monthName,
			number: monthNumbers[monthName.toLowerCase().split(" ")[0]],
			days: daysArray,
		};
	});

	const calendar: Calendar = {
		months: months,
	};

	return calendar;
}

// Example: you would replace 'inputJSON' with the actual JSON data you have
const formattedCalendar = transformData(inputJSON);

// Writing the result to a file
const outputFilePath = "formattedCalendar.json";
fs.writeFile(outputFilePath, JSON.stringify(formattedCalendar, null, 2), (err) => {
	if (err) {
		console.error("Error writing to file", err);
	} else {
		console.log("File has been written successfully");
	}
});
